#############################################################################
# Makefile for building: debug/bin/intensecoin-wallet-gui
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  intensecoin-wallet-gui.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile intensecoin-wallet-gui.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_DECLARATIVE_DEBUG -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -std=c++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Iintense/include -Isrc/libwalletqt -Isrc/QR-Code-generator -Isrc -Iintense/src -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtQuick -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtQml -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = intensecoin-wallet-gui1.0.0
DISTDIR = /home/laion/Desktop/alfasoft/intensecoinwallet/.tmp/intensecoin-wallet-gui1.0.0
LINK          = g++
LFLAGS        = -m64
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -L/home/laion/Desktop/alfasoft/intensecoinwallet/intense/lib -lwallet_merged -lepee -lunbound -leasylogging -lboost_serialization -lboost_thread -lboost_system -lboost_date_time -lboost_filesystem -lboost_regex -lboost_chrono -lboost_program_options -lssl -lcrypto -Wl,-Bdynamic -Wl,-Bdynamic -lunwind -ldl -lQt5Quick -lQt5Widgets -lQt5Gui -lQt5Qml -lQt5Network -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		filter.cpp \
		clipboardAdapter.cpp \
		oscursor.cpp \
		src/libwalletqt/WalletManager.cpp \
		src/libwalletqt/Wallet.cpp \
		src/libwalletqt/PendingTransaction.cpp \
		src/libwalletqt/TransactionHistory.cpp \
		src/libwalletqt/TransactionInfo.cpp \
		src/libwalletqt/QRCodeImageProvider.cpp \
		oshelper.cpp \
		TranslationManager.cpp \
		src/model/TransactionHistoryModel.cpp \
		src/model/TransactionHistorySortFilterModel.cpp \
		src/QR-Code-generator/BitBuffer.cpp \
		src/QR-Code-generator/QrCode.cpp \
		src/QR-Code-generator/QrSegment.cpp \
		src/model/AddressBookModel.cpp \
		src/libwalletqt/AddressBook.cpp \
		src/zxcvbn-c/zxcvbn.c \
		src/libwalletqt/UnsignedTransaction.cpp \
		MainApp.cpp \
		src/daemon/DaemonManager.cpp qrc_qml.cpp \
		moc_filter.cpp \
		moc_clipboardAdapter.cpp \
		moc_oscursor.cpp \
		moc_WalletManager.cpp \
		moc_Wallet.cpp \
		moc_PendingTransaction.cpp \
		moc_TransactionHistory.cpp \
		moc_TransactionInfo.cpp \
		moc_Transfer.cpp \
		moc_oshelper.cpp \
		moc_TranslationManager.cpp \
		moc_TransactionHistoryModel.cpp \
		moc_TransactionHistorySortFilterModel.cpp \
		moc_AddressBookModel.cpp \
		moc_AddressBook.cpp \
		moc_UnsignedTransaction.cpp \
		moc_MainApp.cpp \
		moc_DaemonManager.cpp
OBJECTS       = main.o \
		filter.o \
		clipboardAdapter.o \
		oscursor.o \
		WalletManager.o \
		Wallet.o \
		PendingTransaction.o \
		TransactionHistory.o \
		TransactionInfo.o \
		QRCodeImageProvider.o \
		oshelper.o \
		TranslationManager.o \
		TransactionHistoryModel.o \
		TransactionHistorySortFilterModel.o \
		BitBuffer.o \
		QrCode.o \
		QrSegment.o \
		AddressBookModel.o \
		AddressBook.o \
		zxcvbn.o \
		UnsignedTransaction.o \
		MainApp.o \
		DaemonManager.o \
		qrc_qml.o \
		moc_filter.o \
		moc_clipboardAdapter.o \
		moc_oscursor.o \
		moc_WalletManager.o \
		moc_Wallet.o \
		moc_PendingTransaction.o \
		moc_TransactionHistory.o \
		moc_TransactionInfo.o \
		moc_Transfer.o \
		moc_oshelper.o \
		moc_TranslationManager.o \
		moc_TransactionHistoryModel.o \
		moc_TransactionHistorySortFilterModel.o \
		moc_AddressBookModel.o \
		moc_AddressBook.o \
		moc_UnsignedTransaction.o \
		moc_MainApp.o \
		moc_DaemonManager.o
DIST          = notes.txt \
		intense/src/wallet/CMakeLists.txt \
		components/MobileHeader.qml \
		pages/intense.qml \
		pages/IntenseDashboard.qml \
		IntenseConfig.js \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcollision.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3drenderer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_contacts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_organizer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_versit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_versitorganizer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		deployment.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/declarative_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		intensecoin-wallet-gui.pro filter.h \
		clipboardAdapter.h \
		oscursor.h \
		src/libwalletqt/WalletManager.h \
		src/libwalletqt/Wallet.h \
		src/libwalletqt/PendingTransaction.h \
		src/libwalletqt/TransactionHistory.h \
		src/libwalletqt/TransactionInfo.h \
		src/libwalletqt/QRCodeImageProvider.h \
		src/libwalletqt/Transfer.h \
		oshelper.h \
		TranslationManager.h \
		src/model/TransactionHistoryModel.h \
		src/model/TransactionHistorySortFilterModel.h \
		src/QR-Code-generator/BitBuffer.hpp \
		src/QR-Code-generator/QrCode.hpp \
		src/QR-Code-generator/QrSegment.hpp \
		src/model/AddressBookModel.h \
		src/libwalletqt/AddressBook.h \
		src/zxcvbn-c/zxcvbn.h \
		src/libwalletqt/UnsignedTransaction.h \
		MainApp.h \
		src/daemon/DaemonManager.h main.cpp \
		filter.cpp \
		clipboardAdapter.cpp \
		oscursor.cpp \
		src/libwalletqt/WalletManager.cpp \
		src/libwalletqt/Wallet.cpp \
		src/libwalletqt/PendingTransaction.cpp \
		src/libwalletqt/TransactionHistory.cpp \
		src/libwalletqt/TransactionInfo.cpp \
		src/libwalletqt/QRCodeImageProvider.cpp \
		oshelper.cpp \
		TranslationManager.cpp \
		src/model/TransactionHistoryModel.cpp \
		src/model/TransactionHistorySortFilterModel.cpp \
		src/QR-Code-generator/BitBuffer.cpp \
		src/QR-Code-generator/QrCode.cpp \
		src/QR-Code-generator/QrSegment.cpp \
		src/model/AddressBookModel.cpp \
		src/libwalletqt/AddressBook.cpp \
		src/zxcvbn-c/zxcvbn.c \
		src/libwalletqt/UnsignedTransaction.cpp \
		MainApp.cpp \
		src/daemon/DaemonManager.cpp
QMAKE_TARGET  = intensecoin-wallet-gui
DESTDIR       = debug/bin/#avoid trailing-slash linebreak
TARGET        = debug/bin/intensecoin-wallet-gui


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): langupd compiler_langrel_make_all $(OBJECTS)  
	@test -d debug/bin/ || mkdir -p debug/bin/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: intensecoin-wallet-gui.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcollision.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3drenderer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_contacts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_organizer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_versit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_versitorganizer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		deployment.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/declarative_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		intensecoin-wallet-gui.pro \
		qml.qrc \
		/usr/lib/x86_64-linux-gnu/libQt5Quick.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Qml.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Network.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile intensecoin-wallet-gui.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcollision.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dinput.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickrenderer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3drenderer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_contacts.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_location.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_organizer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_versit.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_versitorganizer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
deployment.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/declarative_debug.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
intensecoin-wallet-gui.pro:
qml.qrc:
/usr/lib/x86_64-linux-gnu/libQt5Quick.prl:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Qml.prl:
/usr/lib/x86_64-linux-gnu/libQt5Network.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile intensecoin-wallet-gui.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents translations/monero-core.ts translations/monero-core_ar.ts translations/monero-core_pt-br.ts translations/monero-core_de.ts translations/monero-core_eo.ts translations/monero-core_es.ts translations/monero-core_fi.ts translations/monero-core_fr.ts translations/monero-core_hr.ts translations/monero-core_id.ts translations/monero-core_hi.ts translations/monero-core_it.ts translations/monero-core_ja.ts translations/monero-core_nl.ts translations/monero-core_pl.ts translations/monero-core_ru.ts translations/monero-core_sv.ts translations/monero-core_zh-cn.ts translations/monero-core_zh-tw.ts translations/monero-core_he.ts translations/monero-core_ko.ts translations/monero-core_ro.ts $(DISTDIR)/
	$(COPY_FILE) --parents qml.qrc $(DISTDIR)/
	$(COPY_FILE) --parents filter.h clipboardAdapter.h oscursor.h src/libwalletqt/WalletManager.h src/libwalletqt/Wallet.h src/libwalletqt/PendingTransaction.h src/libwalletqt/TransactionHistory.h src/libwalletqt/TransactionInfo.h src/libwalletqt/QRCodeImageProvider.h src/libwalletqt/Transfer.h oshelper.h TranslationManager.h src/model/TransactionHistoryModel.h src/model/TransactionHistorySortFilterModel.h src/QR-Code-generator/BitBuffer.hpp src/QR-Code-generator/QrCode.hpp src/QR-Code-generator/QrSegment.hpp src/model/AddressBookModel.h src/libwalletqt/AddressBook.h src/zxcvbn-c/zxcvbn.h src/libwalletqt/UnsignedTransaction.h MainApp.h src/daemon/DaemonManager.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp filter.cpp clipboardAdapter.cpp oscursor.cpp src/libwalletqt/WalletManager.cpp src/libwalletqt/Wallet.cpp src/libwalletqt/PendingTransaction.cpp src/libwalletqt/TransactionHistory.cpp src/libwalletqt/TransactionInfo.cpp src/libwalletqt/QRCodeImageProvider.cpp oshelper.cpp TranslationManager.cpp src/model/TransactionHistoryModel.cpp src/model/TransactionHistorySortFilterModel.cpp src/QR-Code-generator/BitBuffer.cpp src/QR-Code-generator/QrCode.cpp src/QR-Code-generator/QrSegment.cpp src/model/AddressBookModel.cpp src/libwalletqt/AddressBook.cpp src/zxcvbn-c/zxcvbn.c src/libwalletqt/UnsignedTransaction.cpp MainApp.cpp src/daemon/DaemonManager.cpp $(DISTDIR)/
	$(COPY_FILE) --parents translations/monero-core.ts translations/monero-core_ar.ts translations/monero-core_pt-br.ts translations/monero-core_de.ts translations/monero-core_eo.ts translations/monero-core_es.ts translations/monero-core_fi.ts translations/monero-core_fr.ts translations/monero-core_hr.ts translations/monero-core_id.ts translations/monero-core_hi.ts translations/monero-core_it.ts translations/monero-core_ja.ts translations/monero-core_nl.ts translations/monero-core_pl.ts translations/monero-core_ru.ts translations/monero-core_sv.ts translations/monero-core_zh-cn.ts translations/monero-core_zh-tw.ts translations/monero-core_he.ts translations/monero-core_ko.ts translations/monero-core_ro.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) -r /home/laion/Desktop/alfasoft/intensecoinwallet/intense
	-$(DEL_FILE) Makefile


####### Sub-libraries

langupd:

deploy:
	
	 /home/laion/Desktop/alfasoft/intensecoinwallet/linuxdeploy_helper.sh debug/bin intensecoin-wallet-gui

deploy_win:

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_langrel_make_all: debug/bin/translations/monero-core.qm debug/bin/translations/monero-core_ar.qm debug/bin/translations/monero-core_pt-br.qm debug/bin/translations/monero-core_de.qm debug/bin/translations/monero-core_eo.qm debug/bin/translations/monero-core_es.qm debug/bin/translations/monero-core_fi.qm debug/bin/translations/monero-core_fr.qm debug/bin/translations/monero-core_hr.qm debug/bin/translations/monero-core_id.qm debug/bin/translations/monero-core_hi.qm debug/bin/translations/monero-core_it.qm debug/bin/translations/monero-core_ja.qm debug/bin/translations/monero-core_nl.qm debug/bin/translations/monero-core_pl.qm debug/bin/translations/monero-core_ru.qm debug/bin/translations/monero-core_sv.qm debug/bin/translations/monero-core_zh-cn.qm debug/bin/translations/monero-core_zh-tw.qm debug/bin/translations/monero-core_he.qm debug/bin/translations/monero-core_ko.qm debug/bin/translations/monero-core_ro.qm
compiler_langrel_clean:
	-$(DEL_FILE) debug/bin/translations/monero-core.qm debug/bin/translations/monero-core_ar.qm debug/bin/translations/monero-core_pt-br.qm debug/bin/translations/monero-core_de.qm debug/bin/translations/monero-core_eo.qm debug/bin/translations/monero-core_es.qm debug/bin/translations/monero-core_fi.qm debug/bin/translations/monero-core_fr.qm debug/bin/translations/monero-core_hr.qm debug/bin/translations/monero-core_id.qm debug/bin/translations/monero-core_hi.qm debug/bin/translations/monero-core_it.qm debug/bin/translations/monero-core_ja.qm debug/bin/translations/monero-core_nl.qm debug/bin/translations/monero-core_pl.qm debug/bin/translations/monero-core_ru.qm debug/bin/translations/monero-core_sv.qm debug/bin/translations/monero-core_zh-cn.qm debug/bin/translations/monero-core_zh-tw.qm debug/bin/translations/monero-core_he.qm debug/bin/translations/monero-core_ko.qm debug/bin/translations/monero-core_ro.qm
debug/bin/translations/monero-core.qm: translations/monero-core.ts \
		langupd
	/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease translations/monero-core.ts -qm /home/laion/Desktop/alfasoft/intensecoinwallet/debug/bin/translations/monero-core.qm

debug/bin/translations/monero-core_ar.qm: translations/monero-core_ar.ts \
		langupd
	/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease translations/monero-core_ar.ts -qm /home/laion/Desktop/alfasoft/intensecoinwallet/debug/bin/translations/monero-core_ar.qm

debug/bin/translations/monero-core_pt-br.qm: translations/monero-core_pt-br.ts \
		langupd
	/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease translations/monero-core_pt-br.ts -qm /home/laion/Desktop/alfasoft/intensecoinwallet/debug/bin/translations/monero-core_pt-br.qm

debug/bin/translations/monero-core_de.qm: translations/monero-core_de.ts \
		langupd
	/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease translations/monero-core_de.ts -qm /home/laion/Desktop/alfasoft/intensecoinwallet/debug/bin/translations/monero-core_de.qm

debug/bin/translations/monero-core_eo.qm: translations/monero-core_eo.ts \
		langupd
	/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease translations/monero-core_eo.ts -qm /home/laion/Desktop/alfasoft/intensecoinwallet/debug/bin/translations/monero-core_eo.qm

debug/bin/translations/monero-core_es.qm: translations/monero-core_es.ts \
		langupd
	/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease translations/monero-core_es.ts -qm /home/laion/Desktop/alfasoft/intensecoinwallet/debug/bin/translations/monero-core_es.qm

debug/bin/translations/monero-core_fi.qm: translations/monero-core_fi.ts \
		langupd
	/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease translations/monero-core_fi.ts -qm /home/laion/Desktop/alfasoft/intensecoinwallet/debug/bin/translations/monero-core_fi.qm

debug/bin/translations/monero-core_fr.qm: translations/monero-core_fr.ts \
		langupd
	/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease translations/monero-core_fr.ts -qm /home/laion/Desktop/alfasoft/intensecoinwallet/debug/bin/translations/monero-core_fr.qm

debug/bin/translations/monero-core_hr.qm: translations/monero-core_hr.ts \
		langupd
	/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease translations/monero-core_hr.ts -qm /home/laion/Desktop/alfasoft/intensecoinwallet/debug/bin/translations/monero-core_hr.qm

debug/bin/translations/monero-core_id.qm: translations/monero-core_id.ts \
		langupd
	/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease translations/monero-core_id.ts -qm /home/laion/Desktop/alfasoft/intensecoinwallet/debug/bin/translations/monero-core_id.qm

debug/bin/translations/monero-core_hi.qm: translations/monero-core_hi.ts \
		langupd
	/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease translations/monero-core_hi.ts -qm /home/laion/Desktop/alfasoft/intensecoinwallet/debug/bin/translations/monero-core_hi.qm

debug/bin/translations/monero-core_it.qm: translations/monero-core_it.ts \
		langupd
	/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease translations/monero-core_it.ts -qm /home/laion/Desktop/alfasoft/intensecoinwallet/debug/bin/translations/monero-core_it.qm

debug/bin/translations/monero-core_ja.qm: translations/monero-core_ja.ts \
		langupd
	/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease translations/monero-core_ja.ts -qm /home/laion/Desktop/alfasoft/intensecoinwallet/debug/bin/translations/monero-core_ja.qm

debug/bin/translations/monero-core_nl.qm: translations/monero-core_nl.ts \
		langupd
	/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease translations/monero-core_nl.ts -qm /home/laion/Desktop/alfasoft/intensecoinwallet/debug/bin/translations/monero-core_nl.qm

debug/bin/translations/monero-core_pl.qm: translations/monero-core_pl.ts \
		langupd
	/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease translations/monero-core_pl.ts -qm /home/laion/Desktop/alfasoft/intensecoinwallet/debug/bin/translations/monero-core_pl.qm

debug/bin/translations/monero-core_ru.qm: translations/monero-core_ru.ts \
		langupd
	/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease translations/monero-core_ru.ts -qm /home/laion/Desktop/alfasoft/intensecoinwallet/debug/bin/translations/monero-core_ru.qm

debug/bin/translations/monero-core_sv.qm: translations/monero-core_sv.ts \
		langupd
	/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease translations/monero-core_sv.ts -qm /home/laion/Desktop/alfasoft/intensecoinwallet/debug/bin/translations/monero-core_sv.qm

debug/bin/translations/monero-core_zh-cn.qm: translations/monero-core_zh-cn.ts \
		langupd
	/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease translations/monero-core_zh-cn.ts -qm /home/laion/Desktop/alfasoft/intensecoinwallet/debug/bin/translations/monero-core_zh-cn.qm

debug/bin/translations/monero-core_zh-tw.qm: translations/monero-core_zh-tw.ts \
		langupd
	/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease translations/monero-core_zh-tw.ts -qm /home/laion/Desktop/alfasoft/intensecoinwallet/debug/bin/translations/monero-core_zh-tw.qm

debug/bin/translations/monero-core_he.qm: translations/monero-core_he.ts \
		langupd
	/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease translations/monero-core_he.ts -qm /home/laion/Desktop/alfasoft/intensecoinwallet/debug/bin/translations/monero-core_he.qm

debug/bin/translations/monero-core_ko.qm: translations/monero-core_ko.ts \
		langupd
	/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease translations/monero-core_ko.ts -qm /home/laion/Desktop/alfasoft/intensecoinwallet/debug/bin/translations/monero-core_ko.qm

debug/bin/translations/monero-core_ro.qm: translations/monero-core_ro.ts \
		langupd
	/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease translations/monero-core_ro.ts -qm /home/laion/Desktop/alfasoft/intensecoinwallet/debug/bin/translations/monero-core_ro.qm

compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		RightPanel.qml \
		IntenseConfig.js \
		LeftPanel.qml \
		version.js \
		MiddlePanel.qml \
		BasicPanel.qml \
		main.qml \
		images/uncheckedIcon.png \
		images/tip.png \
		images/moneroLogo2.png \
		images/wgshield.png \
		images/star.png \
		images/unstar.png \
		images/statusConnected.png \
		images/closeIcon.png \
		images/moneroIcon.png \
		images/dropdownDel.png \
		images/createWallet.png \
		images/openAccount.png \
		images/nextMonth.png \
		images/descSortIndicator.png \
		images/ascSortIndicator.png \
		images/statusDisconnected.png \
		images/maximizeIcon.png \
		images/ascSortIndicatorActived.png \
		images/descSortIndicatorActived.png \
		images/vgshield.png \
		images/recoverWallet.png \
		images/expandTable.png \
		images/dropdownCopy.png \
		images/ascSortIndicatorPressed.png \
		images/deleteIcon.png \
		images/descSortIndicatorPressed.png \
		images/dropIndicator.png \
		images/goToBasicVersionHovered.png \
		images/whiteDropIndicator.png \
		images/dropdownAdd.png \
		images/expandRightPanel.png \
		images/hseparator.png \
		images/poff.png \
		images/menuIndicator.png \
		images/privacyTick.png \
		images/tableOptions.png \
		images/checkedVioletIcon.png \
		images/collapseRightPanel.png \
		images/magnifier.png \
		images/prevPage.png \
		images/helpIcon.png \
		images/resize.png \
		images/lockIcon.png \
		images/checkedOrangeIcon.png \
		images/minimizeIcon.png \
		images/prevMonth.png \
		images/resizeHovered.png \
		images/gotoBasicVersion.png \
		images/dropdownSearch.png \
		images/moneroLogo.png \
		images/greyTriangle.png \
		images/backToWindowIcon.png \
		images/datePicker.png \
		images/nextPage.png \
		images/copyToClipboard.png \
		images/shield.png \
		images/pon.png \
		images/whatIsIcon.png \
		images/dropdownSend.png \
		wizard/WizardConfigure.qml \
		wizard/WizardCreateViewOnlyWallet.qml \
		wizard/WizardPassword.qml \
		wizard/WizardPasswordInput.qml \
		wizard/WizardMain.qml \
		wizard/WizardRecoveryWallet.qml \
		wizard/WizardOptions.qml \
		wizard/WizardManageWalletUI.qml \
		wizard/WizardMemoTextInput.qml \
		wizard/utils.js \
		wizard/WizardWelcome.qml \
		wizard/WizardCreateWallet.qml \
		wizard/WizardFinish.qml \
		wizard/WizardDonation.qml \
		wizard/WizardPasswordUI.qml \
		tabs/Twitter.qml \
		tabs/tweetSearch.js \
		tabs/TweetsModel.qml \
		lang/languages.xml \
		lang/flags/brazil.png \
		lang/flags/india.png \
		lang/flags/italy.png \
		lang/flags/spain.png \
		lang/flags/croatia.png \
		lang/flags/bangladesh.png \
		lang/flags/rpa.png \
		lang/flags/finland.png \
		lang/flags/france.png \
		lang/flags/german.png \
		lang/flags/netherlands.png \
		lang/flags/uk.png \
		lang/flags/israel.png \
		lang/flags/china.png \
		lang/flags/south_korea.png \
		lang/flags/poland.png \
		lang/flags/sweden.png \
		lang/flags/indonesia.png \
		lang/flags/palestine.png \
		lang/flags/usa.png \
		lang/flags/russia.png \
		lang/flags/esperanto.png \
		lang/flags/romania.png \
		lang/flags/japan.png \
		lang/flags/taiwan.png \
		components/PrivacyLevel.qml \
		components/TextBlock.qml \
		components/TipItem.qml \
		components/StandardButton.qml \
		components/NetworkStatusItem.qml \
		components/Notifier.qml \
		components/TableHeader.qml \
		components/StandardDropdown.qml \
		components/DatePicker.qml \
		components/IntenseTable.qml \
		components/DaemonManagerDialog.qml \
		components/IconButton.qml \
		components/DaemonConsole.qml \
		components/Input.qml \
		components/StandardDialog.qml \
		components/SearchInput.qml \
		components/LineEdit.qml \
		components/PrivacyLevelSmall.qml \
		components/AddressBookTable.qml \
		components/Label.qml \
		components/TableDropdown.qml \
		components/DashboardTable.qml \
		components/PasswordDialog.qml \
		components/IntenseHeader.qml \
		components/MobileHeader.qml \
		components/Scroll.qml \
		components/ProgressBar.qml \
		components/TitleBar.qml \
		components/ProcessingSplash.qml \
		components/MenuButton.qml \
		components/HistoryTable.qml \
		components/CheckBox.qml \
		components/QRCodeScanner.qml \
		components/TickDelegate.qml \
		pages/Transfer.qml \
		pages/Mining.qml \
		pages/Sign.qml \
		pages/AddressBook.qml \
		pages/Dashboard.qml \
		pages/Settings.qml \
		pages/History.qml \
		pages/IntenseDashboard.qml \
		pages/Receive.qml \
		pages/Intense.qml \
		pages/TxKey.qml
	/usr/lib/x86_64-linux-gnu/qt5/bin/rcc -name qml qml.qrc -o qrc_qml.cpp

compiler_moc_header_make_all: moc_filter.cpp moc_clipboardAdapter.cpp moc_oscursor.cpp moc_WalletManager.cpp moc_Wallet.cpp moc_PendingTransaction.cpp moc_TransactionHistory.cpp moc_TransactionInfo.cpp moc_Transfer.cpp moc_oshelper.cpp moc_TranslationManager.cpp moc_TransactionHistoryModel.cpp moc_TransactionHistorySortFilterModel.cpp moc_AddressBookModel.cpp moc_AddressBook.cpp moc_UnsignedTransaction.cpp moc_MainApp.cpp moc_DaemonManager.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_filter.cpp moc_clipboardAdapter.cpp moc_oscursor.cpp moc_WalletManager.cpp moc_Wallet.cpp moc_PendingTransaction.cpp moc_TransactionHistory.cpp moc_TransactionInfo.cpp moc_Transfer.cpp moc_oshelper.cpp moc_TranslationManager.cpp moc_TransactionHistoryModel.cpp moc_TransactionHistorySortFilterModel.cpp moc_AddressBookModel.cpp moc_AddressBook.cpp moc_UnsignedTransaction.cpp moc_MainApp.cpp moc_DaemonManager.cpp
moc_filter.cpp: filter.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/laion/Desktop/alfasoft/intensecoinwallet -I/home/laion/Desktop/alfasoft/intensecoinwallet/intense/include -I/home/laion/Desktop/alfasoft/intensecoinwallet/src/libwalletqt -I/home/laion/Desktop/alfasoft/intensecoinwallet/src/QR-Code-generator -I/home/laion/Desktop/alfasoft/intensecoinwallet/src -I/home/laion/Desktop/alfasoft/intensecoinwallet/intense/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include filter.h -o moc_filter.cpp

moc_clipboardAdapter.cpp: clipboardAdapter.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/laion/Desktop/alfasoft/intensecoinwallet -I/home/laion/Desktop/alfasoft/intensecoinwallet/intense/include -I/home/laion/Desktop/alfasoft/intensecoinwallet/src/libwalletqt -I/home/laion/Desktop/alfasoft/intensecoinwallet/src/QR-Code-generator -I/home/laion/Desktop/alfasoft/intensecoinwallet/src -I/home/laion/Desktop/alfasoft/intensecoinwallet/intense/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include clipboardAdapter.h -o moc_clipboardAdapter.cpp

moc_oscursor.cpp: oscursor.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/laion/Desktop/alfasoft/intensecoinwallet -I/home/laion/Desktop/alfasoft/intensecoinwallet/intense/include -I/home/laion/Desktop/alfasoft/intensecoinwallet/src/libwalletqt -I/home/laion/Desktop/alfasoft/intensecoinwallet/src/QR-Code-generator -I/home/laion/Desktop/alfasoft/intensecoinwallet/src -I/home/laion/Desktop/alfasoft/intensecoinwallet/intense/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include oscursor.h -o moc_oscursor.cpp

moc_WalletManager.cpp: intense/include/wallet/wallet2_api.h \
		src/libwalletqt/WalletManager.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/laion/Desktop/alfasoft/intensecoinwallet -I/home/laion/Desktop/alfasoft/intensecoinwallet/intense/include -I/home/laion/Desktop/alfasoft/intensecoinwallet/src/libwalletqt -I/home/laion/Desktop/alfasoft/intensecoinwallet/src/QR-Code-generator -I/home/laion/Desktop/alfasoft/intensecoinwallet/src -I/home/laion/Desktop/alfasoft/intensecoinwallet/intense/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/libwalletqt/WalletManager.h -o moc_WalletManager.cpp

moc_Wallet.cpp: intense/include/wallet/wallet2_api.h \
		src/libwalletqt/PendingTransaction.h \
		src/libwalletqt/UnsignedTransaction.h \
		src/libwalletqt/Wallet.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/laion/Desktop/alfasoft/intensecoinwallet -I/home/laion/Desktop/alfasoft/intensecoinwallet/intense/include -I/home/laion/Desktop/alfasoft/intensecoinwallet/src/libwalletqt -I/home/laion/Desktop/alfasoft/intensecoinwallet/src/QR-Code-generator -I/home/laion/Desktop/alfasoft/intensecoinwallet/src -I/home/laion/Desktop/alfasoft/intensecoinwallet/intense/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/libwalletqt/Wallet.h -o moc_Wallet.cpp

moc_PendingTransaction.cpp: intense/include/wallet/wallet2_api.h \
		src/libwalletqt/PendingTransaction.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/laion/Desktop/alfasoft/intensecoinwallet -I/home/laion/Desktop/alfasoft/intensecoinwallet/intense/include -I/home/laion/Desktop/alfasoft/intensecoinwallet/src/libwalletqt -I/home/laion/Desktop/alfasoft/intensecoinwallet/src/QR-Code-generator -I/home/laion/Desktop/alfasoft/intensecoinwallet/src -I/home/laion/Desktop/alfasoft/intensecoinwallet/intense/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/libwalletqt/PendingTransaction.h -o moc_PendingTransaction.cpp

moc_TransactionHistory.cpp: src/libwalletqt/TransactionHistory.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/laion/Desktop/alfasoft/intensecoinwallet -I/home/laion/Desktop/alfasoft/intensecoinwallet/intense/include -I/home/laion/Desktop/alfasoft/intensecoinwallet/src/libwalletqt -I/home/laion/Desktop/alfasoft/intensecoinwallet/src/QR-Code-generator -I/home/laion/Desktop/alfasoft/intensecoinwallet/src -I/home/laion/Desktop/alfasoft/intensecoinwallet/intense/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/libwalletqt/TransactionHistory.h -o moc_TransactionHistory.cpp

moc_TransactionInfo.cpp: intense/include/wallet/wallet2_api.h \
		src/libwalletqt/TransactionInfo.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/laion/Desktop/alfasoft/intensecoinwallet -I/home/laion/Desktop/alfasoft/intensecoinwallet/intense/include -I/home/laion/Desktop/alfasoft/intensecoinwallet/src/libwalletqt -I/home/laion/Desktop/alfasoft/intensecoinwallet/src/QR-Code-generator -I/home/laion/Desktop/alfasoft/intensecoinwallet/src -I/home/laion/Desktop/alfasoft/intensecoinwallet/intense/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/libwalletqt/TransactionInfo.h -o moc_TransactionInfo.cpp

moc_Transfer.cpp: intense/include/wallet/wallet2_api.h \
		src/libwalletqt/Transfer.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/laion/Desktop/alfasoft/intensecoinwallet -I/home/laion/Desktop/alfasoft/intensecoinwallet/intense/include -I/home/laion/Desktop/alfasoft/intensecoinwallet/src/libwalletqt -I/home/laion/Desktop/alfasoft/intensecoinwallet/src/QR-Code-generator -I/home/laion/Desktop/alfasoft/intensecoinwallet/src -I/home/laion/Desktop/alfasoft/intensecoinwallet/intense/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/libwalletqt/Transfer.h -o moc_Transfer.cpp

moc_oshelper.cpp: oshelper.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/laion/Desktop/alfasoft/intensecoinwallet -I/home/laion/Desktop/alfasoft/intensecoinwallet/intense/include -I/home/laion/Desktop/alfasoft/intensecoinwallet/src/libwalletqt -I/home/laion/Desktop/alfasoft/intensecoinwallet/src/QR-Code-generator -I/home/laion/Desktop/alfasoft/intensecoinwallet/src -I/home/laion/Desktop/alfasoft/intensecoinwallet/intense/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include oshelper.h -o moc_oshelper.cpp

moc_TranslationManager.cpp: TranslationManager.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/laion/Desktop/alfasoft/intensecoinwallet -I/home/laion/Desktop/alfasoft/intensecoinwallet/intense/include -I/home/laion/Desktop/alfasoft/intensecoinwallet/src/libwalletqt -I/home/laion/Desktop/alfasoft/intensecoinwallet/src/QR-Code-generator -I/home/laion/Desktop/alfasoft/intensecoinwallet/src -I/home/laion/Desktop/alfasoft/intensecoinwallet/intense/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include TranslationManager.h -o moc_TranslationManager.cpp

moc_TransactionHistoryModel.cpp: src/model/TransactionHistoryModel.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/laion/Desktop/alfasoft/intensecoinwallet -I/home/laion/Desktop/alfasoft/intensecoinwallet/intense/include -I/home/laion/Desktop/alfasoft/intensecoinwallet/src/libwalletqt -I/home/laion/Desktop/alfasoft/intensecoinwallet/src/QR-Code-generator -I/home/laion/Desktop/alfasoft/intensecoinwallet/src -I/home/laion/Desktop/alfasoft/intensecoinwallet/intense/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/model/TransactionHistoryModel.h -o moc_TransactionHistoryModel.cpp

moc_TransactionHistorySortFilterModel.cpp: src/libwalletqt/TransactionInfo.h \
		intense/include/wallet/wallet2_api.h \
		src/model/TransactionHistorySortFilterModel.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/laion/Desktop/alfasoft/intensecoinwallet -I/home/laion/Desktop/alfasoft/intensecoinwallet/intense/include -I/home/laion/Desktop/alfasoft/intensecoinwallet/src/libwalletqt -I/home/laion/Desktop/alfasoft/intensecoinwallet/src/QR-Code-generator -I/home/laion/Desktop/alfasoft/intensecoinwallet/src -I/home/laion/Desktop/alfasoft/intensecoinwallet/intense/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/model/TransactionHistorySortFilterModel.h -o moc_TransactionHistorySortFilterModel.cpp

moc_AddressBookModel.cpp: src/model/AddressBookModel.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/laion/Desktop/alfasoft/intensecoinwallet -I/home/laion/Desktop/alfasoft/intensecoinwallet/intense/include -I/home/laion/Desktop/alfasoft/intensecoinwallet/src/libwalletqt -I/home/laion/Desktop/alfasoft/intensecoinwallet/src/QR-Code-generator -I/home/laion/Desktop/alfasoft/intensecoinwallet/src -I/home/laion/Desktop/alfasoft/intensecoinwallet/intense/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/model/AddressBookModel.h -o moc_AddressBookModel.cpp

moc_AddressBook.cpp: intense/include/wallet/wallet2_api.h \
		src/libwalletqt/AddressBook.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/laion/Desktop/alfasoft/intensecoinwallet -I/home/laion/Desktop/alfasoft/intensecoinwallet/intense/include -I/home/laion/Desktop/alfasoft/intensecoinwallet/src/libwalletqt -I/home/laion/Desktop/alfasoft/intensecoinwallet/src/QR-Code-generator -I/home/laion/Desktop/alfasoft/intensecoinwallet/src -I/home/laion/Desktop/alfasoft/intensecoinwallet/intense/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/libwalletqt/AddressBook.h -o moc_AddressBook.cpp

moc_UnsignedTransaction.cpp: intense/include/wallet/wallet2_api.h \
		src/libwalletqt/UnsignedTransaction.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/laion/Desktop/alfasoft/intensecoinwallet -I/home/laion/Desktop/alfasoft/intensecoinwallet/intense/include -I/home/laion/Desktop/alfasoft/intensecoinwallet/src/libwalletqt -I/home/laion/Desktop/alfasoft/intensecoinwallet/src/QR-Code-generator -I/home/laion/Desktop/alfasoft/intensecoinwallet/src -I/home/laion/Desktop/alfasoft/intensecoinwallet/intense/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/libwalletqt/UnsignedTransaction.h -o moc_UnsignedTransaction.cpp

moc_MainApp.cpp: MainApp.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/laion/Desktop/alfasoft/intensecoinwallet -I/home/laion/Desktop/alfasoft/intensecoinwallet/intense/include -I/home/laion/Desktop/alfasoft/intensecoinwallet/src/libwalletqt -I/home/laion/Desktop/alfasoft/intensecoinwallet/src/QR-Code-generator -I/home/laion/Desktop/alfasoft/intensecoinwallet/src -I/home/laion/Desktop/alfasoft/intensecoinwallet/intense/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include MainApp.h -o moc_MainApp.cpp

moc_DaemonManager.cpp: src/daemon/DaemonManager.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/laion/Desktop/alfasoft/intensecoinwallet -I/home/laion/Desktop/alfasoft/intensecoinwallet/intense/include -I/home/laion/Desktop/alfasoft/intensecoinwallet/src/libwalletqt -I/home/laion/Desktop/alfasoft/intensecoinwallet/src/QR-Code-generator -I/home/laion/Desktop/alfasoft/intensecoinwallet/src -I/home/laion/Desktop/alfasoft/intensecoinwallet/intense/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/daemon/DaemonManager.h -o moc_DaemonManager.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_langrel_clean compiler_rcc_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp clipboardAdapter.h \
		filter.h \
		oscursor.h \
		oshelper.h \
		src/libwalletqt/WalletManager.h \
		intense/include/wallet/wallet2_api.h \
		src/libwalletqt/Wallet.h \
		src/libwalletqt/PendingTransaction.h \
		src/libwalletqt/UnsignedTransaction.h \
		src/libwalletqt/QRCodeImageProvider.h \
		TranslationManager.h \
		src/libwalletqt/TransactionInfo.h \
		src/libwalletqt/TransactionHistory.h \
		src/model/TransactionHistoryModel.h \
		src/model/TransactionHistorySortFilterModel.h \
		src/libwalletqt/AddressBook.h \
		src/model/AddressBookModel.h \
		MainApp.h \
		src/daemon/DaemonManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

filter.o: filter.cpp filter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filter.o filter.cpp

clipboardAdapter.o: clipboardAdapter.cpp clipboardAdapter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clipboardAdapter.o clipboardAdapter.cpp

oscursor.o: oscursor.cpp oscursor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o oscursor.o oscursor.cpp

WalletManager.o: src/libwalletqt/WalletManager.cpp src/libwalletqt/WalletManager.h \
		intense/include/wallet/wallet2_api.h \
		src/libwalletqt/Wallet.h \
		src/libwalletqt/PendingTransaction.h \
		src/libwalletqt/UnsignedTransaction.h \
		src/zxcvbn-c/zxcvbn.h \
		src/libwalletqt/QRCodeImageProvider.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o WalletManager.o src/libwalletqt/WalletManager.cpp

Wallet.o: src/libwalletqt/Wallet.cpp src/libwalletqt/Wallet.h \
		intense/include/wallet/wallet2_api.h \
		src/libwalletqt/PendingTransaction.h \
		src/libwalletqt/UnsignedTransaction.h \
		src/libwalletqt/TransactionHistory.h \
		src/libwalletqt/AddressBook.h \
		src/model/TransactionHistoryModel.h \
		src/model/TransactionHistorySortFilterModel.h \
		src/libwalletqt/TransactionInfo.h \
		src/model/AddressBookModel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Wallet.o src/libwalletqt/Wallet.cpp

PendingTransaction.o: src/libwalletqt/PendingTransaction.cpp src/libwalletqt/PendingTransaction.h \
		intense/include/wallet/wallet2_api.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PendingTransaction.o src/libwalletqt/PendingTransaction.cpp

TransactionHistory.o: src/libwalletqt/TransactionHistory.cpp src/libwalletqt/TransactionHistory.h \
		src/libwalletqt/TransactionInfo.h \
		intense/include/wallet/wallet2_api.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TransactionHistory.o src/libwalletqt/TransactionHistory.cpp

TransactionInfo.o: src/libwalletqt/TransactionInfo.cpp src/libwalletqt/TransactionInfo.h \
		intense/include/wallet/wallet2_api.h \
		src/libwalletqt/WalletManager.h \
		src/libwalletqt/Transfer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TransactionInfo.o src/libwalletqt/TransactionInfo.cpp

QRCodeImageProvider.o: src/libwalletqt/QRCodeImageProvider.cpp src/QR-Code-generator/QrCode.hpp \
		src/QR-Code-generator/QrSegment.hpp \
		src/libwalletqt/QRCodeImageProvider.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QRCodeImageProvider.o src/libwalletqt/QRCodeImageProvider.cpp

oshelper.o: oshelper.cpp oshelper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o oshelper.o oshelper.cpp

TranslationManager.o: TranslationManager.cpp TranslationManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TranslationManager.o TranslationManager.cpp

TransactionHistoryModel.o: src/model/TransactionHistoryModel.cpp src/model/TransactionHistoryModel.h \
		src/libwalletqt/TransactionHistory.h \
		src/libwalletqt/TransactionInfo.h \
		intense/include/wallet/wallet2_api.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TransactionHistoryModel.o src/model/TransactionHistoryModel.cpp

TransactionHistorySortFilterModel.o: src/model/TransactionHistorySortFilterModel.cpp src/model/TransactionHistorySortFilterModel.h \
		src/libwalletqt/TransactionInfo.h \
		intense/include/wallet/wallet2_api.h \
		src/model/TransactionHistoryModel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TransactionHistorySortFilterModel.o src/model/TransactionHistorySortFilterModel.cpp

BitBuffer.o: src/QR-Code-generator/BitBuffer.cpp src/QR-Code-generator/BitBuffer.hpp \
		src/QR-Code-generator/QrSegment.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BitBuffer.o src/QR-Code-generator/BitBuffer.cpp

QrCode.o: src/QR-Code-generator/QrCode.cpp src/QR-Code-generator/BitBuffer.hpp \
		src/QR-Code-generator/QrSegment.hpp \
		src/QR-Code-generator/QrCode.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QrCode.o src/QR-Code-generator/QrCode.cpp

QrSegment.o: src/QR-Code-generator/QrSegment.cpp src/QR-Code-generator/BitBuffer.hpp \
		src/QR-Code-generator/QrSegment.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QrSegment.o src/QR-Code-generator/QrSegment.cpp

AddressBookModel.o: src/model/AddressBookModel.cpp src/model/AddressBookModel.h \
		src/libwalletqt/AddressBook.h \
		intense/include/wallet/wallet2_api.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AddressBookModel.o src/model/AddressBookModel.cpp

AddressBook.o: src/libwalletqt/AddressBook.cpp src/libwalletqt/AddressBook.h \
		intense/include/wallet/wallet2_api.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AddressBook.o src/libwalletqt/AddressBook.cpp

zxcvbn.o: src/zxcvbn-c/zxcvbn.c src/zxcvbn-c/zxcvbn.h \
		src/zxcvbn-c/dict-src.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o zxcvbn.o src/zxcvbn-c/zxcvbn.c

UnsignedTransaction.o: src/libwalletqt/UnsignedTransaction.cpp src/libwalletqt/UnsignedTransaction.h \
		intense/include/wallet/wallet2_api.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o UnsignedTransaction.o src/libwalletqt/UnsignedTransaction.cpp

MainApp.o: MainApp.cpp MainApp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainApp.o MainApp.cpp

DaemonManager.o: src/daemon/DaemonManager.cpp src/daemon/DaemonManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DaemonManager.o src/daemon/DaemonManager.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

moc_filter.o: moc_filter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filter.o moc_filter.cpp

moc_clipboardAdapter.o: moc_clipboardAdapter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_clipboardAdapter.o moc_clipboardAdapter.cpp

moc_oscursor.o: moc_oscursor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_oscursor.o moc_oscursor.cpp

moc_WalletManager.o: moc_WalletManager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_WalletManager.o moc_WalletManager.cpp

moc_Wallet.o: moc_Wallet.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Wallet.o moc_Wallet.cpp

moc_PendingTransaction.o: moc_PendingTransaction.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_PendingTransaction.o moc_PendingTransaction.cpp

moc_TransactionHistory.o: moc_TransactionHistory.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TransactionHistory.o moc_TransactionHistory.cpp

moc_TransactionInfo.o: moc_TransactionInfo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TransactionInfo.o moc_TransactionInfo.cpp

moc_Transfer.o: moc_Transfer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Transfer.o moc_Transfer.cpp

moc_oshelper.o: moc_oshelper.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_oshelper.o moc_oshelper.cpp

moc_TranslationManager.o: moc_TranslationManager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TranslationManager.o moc_TranslationManager.cpp

moc_TransactionHistoryModel.o: moc_TransactionHistoryModel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TransactionHistoryModel.o moc_TransactionHistoryModel.cpp

moc_TransactionHistorySortFilterModel.o: moc_TransactionHistorySortFilterModel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TransactionHistorySortFilterModel.o moc_TransactionHistorySortFilterModel.cpp

moc_AddressBookModel.o: moc_AddressBookModel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_AddressBookModel.o moc_AddressBookModel.cpp

moc_AddressBook.o: moc_AddressBook.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_AddressBook.o moc_AddressBook.cpp

moc_UnsignedTransaction.o: moc_UnsignedTransaction.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_UnsignedTransaction.o moc_UnsignedTransaction.cpp

moc_MainApp.o: moc_MainApp.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainApp.o moc_MainApp.cpp

moc_DaemonManager.o: moc_DaemonManager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DaemonManager.o moc_DaemonManager.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/intensecoin-wallet-gui/bin || mkdir -p $(INSTALL_ROOT)/opt/intensecoin-wallet-gui/bin
	-$(INSTALL_PROGRAM) debug/bin/$(QMAKE_TARGET) $(INSTALL_ROOT)/opt/intensecoin-wallet-gui/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/intensecoin-wallet-gui/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/intensecoin-wallet-gui/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

